[pytest]
addopts = -q
testpaths = tests

filterwarnings =
    ignore:'asyncio\.iscoroutinefunction' is deprecated:DeprecationWarning
    ignore:The `dict` method is deprecated; use `model_dump` instead\.:Warning
